version: "3.9"

services:
  web:
    build: ./web
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./web/.env
    volumes:
      - ./app/static/:/app/static/
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: urtyom1
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: my_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

  nginx:
    build: ./nginx
    depends_on:
      - web
    volumes:
      - ./app/static/:/app/static/
    ports:
      - "8000:80"

volumes:
  pgdata:

